name = "Aeronautics Pack"
author = "JesusWazowski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d51ddfa484d1fb7376d762c743ddc26e70dc0a0aa7de6bd4999ee353fbe6386b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
