name = "Aeronautics Testing"
author = "JesusWazowski"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8744d450a02cef5966f7ff6552939e14826f3077d1d7c9cc00ac8379dff16b5d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
