name = "Aeronautics Pack"
author = "JesusWazowski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb5583bd18cccf5b3996935945402cbc17ef870347852e3d61660f2171f50f64"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
